pipelines:
    default:
        - step:
              name: Sync GitHub Mirror
              image: alpine/git:latest
              clone:
                  enabled: false
              script:
                  - git clone --bare git@bitbucket.org:romaswe/pwaDemo.git
                  - cd pwaDemo.git
                  - git push --mirror git@github.com:romaswe/pwaDemo.git
